version: '2'
services:
  loader-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/loader/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=loader
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
